### ISSUE TITLE
Feature: Keywords

### ISSUE THREAD

**Issue by jankout** [Kreativsoehne/Contao_NewsMetaDescription#1]
Hello, 

I thank you very much for the great extension. Would it be possible to extend it for keywords too, please? Or is it easy to do it by myself? 

Thank you.

**Comment by kreativsoehne** [comment]
Hi jankout,

you're welcome :)
It should be not that hard to implement that feature by yourself. Have you ever written a Contao extension? If you did, all you need to do is extend the dca in /system/modules/news_metadescription/dca/tl_news.php with another input field and update /system/modules/news_metadescription/classes/NewsMetaDescription.php to fill up $objPage->keywords with your contents.

I have not tested these changes. If you're familiar with contao extensions please try it by yourself. If you can't get it to work please let me know.

Greetings from Germany,
Michael

**Comment by jankout** [comment]
Ok, a little bit experience I have. I could add the new field and the informations are in the database too. But my command for the output is not correct at the moment. It seems like this

```
class NewsMetaDescription extends \Frontend
{
    public function generateMetaDescription($objPage, $objLayout, $objPageRegular)
    {

        if (!$this->Input->get('items')){
            return; //no news
        }

        $this->import('Database');
        $objArticle = $this->Database->prepare("SELECT meta_description,meta_keywords FROM tl_news WHERE alias=? AND published=1")
                                     ->limit(1)
                                     ->execute($this->Input->get('items'));

        if ($objArticle->numRows < 1){
            return; //not found !!
        }

        global $objPage;

        if ($objArticle->meta_description OR meta_keywords != '' ) {
            $objPage->description = $objArticle->meta_description;
            $objPage->keywords = $objArticle->meta_keywords;
        }

    }
}
```

What should I improve? 

@leofeyer Could you help me, please? Thank you.
@fritzmg Do you have any solution, please?

**Comment by jankout** [comment]
As soon as it works I can send you the whole module and you can offer it to everyone.

**Comment by jankout** [comment]
And is there any help for my case?

**Comment by kreativsoehne** [comment]
Sorry, we are busy at the moment. I'll have a look on it soon.

**Comment by fritzmg** [comment]
Why do you need keywords? The keywords meta tag is sort of deprecated and not (really) used by any Search Engine anymore.

**Comment by jankout** [comment]
For the SEO optimisation would be great at all.

**Comment by fritzmg** [comment]
As I said, it's not relevant for "SEO" anymore. That's why it was removed in Contao as well.

**Comment by jankout** [comment]
But it´s in the article of Contao and in the meta section too. Could you help me or not? ;-) This was my question. I would like to have the solution for my workflow. Thank you.

**Comment by fritzmg** [comment]
Yes, it's still there. In Contao 4, it was removed from the `fe_page` template (see https://github.com/contao/core-bundle/blob/master/UPGRADE.md#meta-keywords), but it can still be entered in the backend, if desired.

Sorry, can't help you at the moment ;)

**Comment by kreativsoehne** [comment]
We've been thinking about your feature request recently and I'm sorry but we've decided to not implement itbecause of it's irrelevance and the lacking support in Contao 4.

**Comment by jankout** [comment]
Yes, I can understand. We can close this issue.
